### ISSUE TITLE
의뢰 상태 변경 시 채팅방에 메시지 전송

### ISSUE THREAD

**Issue by fjeos** [kimjiyooniiiii/BravePeople-Backend#10]
<img width="304" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/f2a46ffa-f4b4-4fa4-892a-8ae3023f058e">

<img width="762" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/98bc59e3-b189-4dd7-808b-312ac0c4f9cc">

프론트 측에서 요청한 대로 의뢰 상태가 변경되거나 채팅방에 입장/퇴장 시 채팅방에 메시지를 전송하는 메서드를 구현했습니다.
(맞게한건진 모름)

<img width="538" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/01a128b9-7e9a-457e-bcf0-3818699f5cc3">
<img width="830" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/ae270415-14a0-4de9-887d-3e211daebf80">
따라서 채팅방 나가기 할 때와 의뢰 완료할 때 위와 같이 수정하였는데 괜찮을까요??
안 괜찮으시면 지우고 push하겠습니다.

그리고 chat 엔티티에 isRead 필드가 삭제된 걸로 알고 있는데, Entity Class에는 아직 남아있어서요.

<img width="199" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/bd4697e5-1605-47ba-bde5-09dd760b5987">
<img width="160" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/f804d1a3-581f-482a-9ba6-dd3f9c4eaa24">
<img width="326" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/cb3b1c35-fb28-4d48-b775-ac21ede32820">

삭제하면 되는 걸까요? DB에는 여전히 저장되고 있습니다.

**Comment by fjeos** [comment]
제가 수정한 부분은 삭제했고 entity에 isRead 필드 삭제해서 push하도록 하겠습니다~~

**Comment by kimjiyooniiiii** [comment]
메시지 전송하는 "공통 메소드"를 나영님이 만들어주시고, 각자 수정하도록 하겠습니다!
