### ISSUE TITLE
채팅방 접속 중 채팅방 리스트 조회 API 호출 시 나의 isRead를 항상 true로 유지하는 방법

### ISSUE THREAD

**Issue by taeho99** [kimjiyooniiiii/BravePeople-Backend#2]
![image](https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/70526479/550a92a3-00b3-4dd5-9fa3-62517d98895c)

프론트 측에서 사진과 같은 의견을 주었습니다. 

채팅방 엔티티에 count 변수를 두고, 채팅방에 2명 다 접속중인 경우 count==2 이므로 이 경우 isRead를 항상 true로 유지하는 방법입니다.
저는 괜찮은 방법같아 보이는데 댓글로 의견 부탁드립니다.

**Comment by taeho99** [comment]
https://kjhoon0330.tistory.com/entry/Spring-%EC%B1%84%ED%8C%85-%EC%9D%BD%EC%9D%8C-%ED%99%95%EC%9D%B8-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0

**Comment by taeho99** [comment]
https://velog.io/@ch4570/Pet-Hub-11-%EC%B1%84%ED%8C%85-%EA%B8%B0%EB%8A%A5%EC%97%90%EC%84%9C-%EC%B1%84%ED%8C%85-%EC%9D%BD%EC%9D%8C-%EC%97%AC%EB%B6%80-%ED%91%9C%EC%8B%9C%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84

**Comment by kimjiyooniiiii** [comment]
그러면 count = 1 일 때는 누가 안읽었는지 여부를 어떻게 알수 있을까요?

**Comment by taeho99** [comment]
count 변수를 도입하여 해결했습니다.
https://github.com/kimjiyooniiiii/BravePeople-Backend/blob/ad0025035a97e65b3c03c6a8f6008b20107bc07c/src/main/java/com/example/brave_people_backend/chat/service/ChatService.java#L80-L86
