### ISSUE TITLE
동시접속으로 인해 채팅방의 count가 0,1,2가 아닌 경우

### ISSUE THREAD

**Issue by taeho99** [kimjiyooniiiii/BravePeople-Backend#4]
정상적인 상황에서는 count가 0,1,2만 존재하게 되지만 동시접속으로 인해 count가 3이 되는 경우가 발생했습니다.

이로 인해 안읽음 처리가 제대로 되지 않았고 잘못된 isRead의 값이 반환됩니다.

어떻게 해결해야 좋을 지 의견 부탁드립니다!

**Comment by kimjiyooniiiii** [comment]
웹소켓 ENTER 시, chatRoom에서 상대ID를 꺼내 session에 저장해두어야 할 것 같습니다. 그렇게 하면 count 변수를 삭제해도 될 것 같습니다. count 변수를 여러명이 공통으로 사용하고 있기에 식별이 어려워 앞으로도 문제가 발생할 가능성이 보입니다.

**Comment by taeho99** [comment]
혹시 session이 HttpSession 같은걸 말하는 걸까요?
아님 Map<Long, Member> sessions; 같이 따로 저장소를 만들어서 하는 걸까요?

> 웹소켓 ENTER 시, chatRoom에서 상대ID를 꺼내 session에 저장해두어야 할 것 같습니다. 그렇게 하면 count 변수를 삭제해도 될 것 같습니다. count 변수를 여러명이 공통으로 사용하고 있기에 식별이 어려워 앞으로도 문제가 발생할 가능성이 보입니다.

**Comment by kimjiyooniiiii** [comment]
<img width="601" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/117561820/f2d9b257-5e81-4106-bb7d-ca1b18534e9c">
이거 입니다!

**Comment by taeho99** [comment]
A랑 B가 접속했을 때 A의 session과 B의 session이 별개인거 같더라고요.
현재 서버에 채팅중인 사람이 만약 10명이라면, 10개의 session(map)이 만들어지는거 같았어요.

그래서 사용자 간에 session이 공유가 안되는데 말씀하신 방법으로 가능할까요?

**Comment by kimjiyooniiiii** [comment]
test
