### ISSUE TITLE
의뢰 기능 응답 데이터의 isActive 필드

### ISSUE THREAD

**Issue by kimjiyooniiiii** [kimjiyooniiiii/BravePeople-Backend#6]
<img width="464" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/117561820/74e310e6-76b4-4761-a37a-c938e1623985">

isActive 필드에 "버튼 활성화"와 같이 간략하게 주석을 달아 놓으면 좋겠습니다!
테이블에 없는 필드라서 의미를 한번에 떠올리기 쉽지 않았습니다!

**Comment by taeho99** [comment]
주석 추가하였습니다. 다음 푸시때 반영됩니다.
