### ISSUE TITLE
Contact 엔티티 삭제여부 필드

### ISSUE THREAD

**Issue by fjeos** [kimjiyooniiiii/BravePeople-Backend#8]
<img width="274" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/97019549/d4c52f45-bcd1-491a-9a7a-dc4074cbbcb3">

Contact 엔티티의 삭제여부 필드가 원래 게시글 삭제할 때 의뢰도 같이 삭제 하려고 만들었던건데
꼭 필요하지 않은거면 없애도 되지 않을까 싶습니다.
게시글 삭제될 때 관련된 의뢰들 상태만 취소로 바꾸면 되지 않을까요?

**Comment by taeho99** [comment]
말씀하신 방법으로 하고 Contact의 삭제여부는 삭제해도 될 듯 합니다!

**Comment by kimjiyooniiiii** [comment]
네 삭제해요!
