### ISSUE TITLE
프로필페이지 API 코드 추가로 member 예외처리 위치 수정 필요

### ISSUE THREAD

**Issue by kimjiyooniiiii** [kimjiyooniiiii/BravePeople-Backend#9]
<img width="802" alt="image" src="https://github.com/kimjiyooniiiii/BravePeople-Backend/assets/117561820/d4d96f9e-0b04-4991-9e1e-9adcc4ca8c26">

태호님! 프로필 페이지 API에 후기, 점수 코드를 추가했는데
후기DB를 검색할때, memberId를 사용해야해서

기존에 맨 밑에 있던 member 예외처리 코드를 위쪽으로 올려주시면 감사하겠습니다!

**Comment by taeho99** [comment]
넵 다음 푸시에 반영하겠습니다.

**Comment by taeho99** [comment]
예외처리 코드를 위로 이동시켜 푸시했습니다.
